#!/bin/bash

# Function to display the help text
function display_help {
    echo "Usage: $0 [options] youtube_url"
    echo
    echo "This script downloads a YouTube video, converts it to audio, transcribes it, chunks the transcription, and generates a summary."
    echo
    echo "Options:"
    echo "--help            Display this help text."
    echo "--stop-download   Stop after downloading the video."
    echo "--stop-conversion Stop after converting the video to audio."
    echo "--stop-transcribe Stop after transcribing the audio."
    echo "--stop-chunk      Stop after chunking the transcription."
}

# Check if no arguments or the --help option was provided
if [ $# -eq 0 ] || [ $1 = "--help" ]; then
    display_help
    exit 0
fi

# Define the YouTube URL
url=$1

# Run the download script
python3 ytget.py "$url"

# Check if the download was successful
if [ $? -ne 0 ] || [ "$2" = "--stop-download" ]; then
    exit $?
fi

# Run the conversion script
bash v2a.sh

# Check if the conversion was successful
if [ $? -ne 0 ] || [ "$2" = "--stop-conversion" ]; then
    exit $?
fi

# Run the transcription script and redirect the output to a file
python3 transcribe.py > transcription.txt
rm output.mp3

# Check if the transcription was successful
if [ $? -ne 0 ] || [ "$2" = "--stop-transcribe" ]; then
    exit $?
fi

# Run the chunking script with the transcription as input
python3 chnk.py transcription.txt

# Check if the chunking was successful
if [ $? -ne 0 ] || [ "$2" = "--stop-chunk" ]; then
    exit $?
fi

# Run the summarization script
python3 summarize.py

# Check if the summarization was successful
if [ $? -ne 0 ]; then
    echo "Error during summarization. Exiting."
    exit 1
fi
